spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        hbm2ddl:
          auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  mvc:
    format:
      date: iso

server:
  port: 8080

elasticsearch:
  url: http://${ELASTIC_HOST}:${ELASTIC_PORT}
